apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test-go-deployment
  labels:
    app: cicd-test-go
spec:
  replicas: 1  # 你可以根据需要调整副本数量
  selector:
    matchLabels:
      app: cicd-test-go
  template:
    metadata:
      labels:
        app: cicd-test-go
    spec:
      containers:
      - name: cicd-test-go
        image: registry.cn-hangzhou.aliyuncs.com/a2/cicd-test-go:55  # 替换为你的实际镜像版本
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: secret-aliyun-key  # 你将创建的镜像拉取秘钥
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-test-go-service
spec:
  type: LoadBalancer  # 也可以根据需要使用 NodePort 或 LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cicd-test-go
